# Name: Faseeh Ahmad

# Roll No: PIAIC95831

# Course: AI

# Batch: 35

In [1]:
import numpy as af
af.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
af.add(4,8)

12

In [3]:
af.subtract(45,30)

15

In [4]:
af.multiply(5,12)

60

In [5]:
af.ones((5,7),dtype=float)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [6]:
af.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
af.arange(3,5,15)

array([3])

In [8]:
af.full((6,4),88)

array([[88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88]])

In [9]:
af.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [10]:
af.random.random((2,8))


array([[0.28364184, 0.37043732, 0.43506048, 0.94140074, 0.53009276,
        0.6009485 , 0.20214234, 0.09596796],
       [0.70041076, 0.87863733, 0.88730876, 0.76999999, 0.42741678,
        0.22914217, 0.74274042, 0.69958682]])

In [11]:
af.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [12]:
af.empty(5)

array([0., 0., 0., 0., 0.])

In [17]:
xyz=af.random.randint(0,10,(2,2))
xyz

array([[2, 8],
       [4, 2]])

In [18]:
abc=af.eye(8)

In [19]:
af.shape(abc)

(8, 8)

In [20]:
af.size(abc)

64

In [21]:
abc.dtype

dtype('float64')

In [24]:
abc.data

In [25]:
abc.ndim

2

In [26]:
abc.itemsize

8

In [27]:
abc.mean()

0.125

In [28]:
abc.sum()

8.0

In [29]:
af.exp(abc)

array([[2.71828183, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 2.71828183, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 2.71828183, 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 2.71828183, 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 2.71828183,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        2.71828183, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 2.71828183, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 2.71828183]])

In [30]:
af.abs(abc)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
acd=4
acd

4

In [33]:
abc.ravel()

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [34]:
af.pi

3.141592653589793

In [35]:
af.sin(acd)

-0.7568024953079282

In [36]:
af.cos(abc)

array([[0.54030231, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 0.54030231, 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 0.54030231,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.54030231]])

In [37]:
af.cos(acd)

-0.6536436208636119

In [38]:
af.tan(acd)

1.1578212823495775

In [40]:
af.arcsin(0.8)

0.9272952180016123

In [41]:
af.log(acd)

1.3862943611198906

In [42]:
af.log2(acd)

2.0

In [43]:
af.log10(acd)

0.6020599913279624

In [45]:
af.add.reduce(acd)

4

In [46]:
af.add.reduce(abc)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
af.multiply.reduce(acd)

4

In [48]:
af.multiply.accumulate(abc)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
af.hsplit(de,3)

[array([[7],
        [2],
        [3]]),
 array([[6],
        [2],
        [4]]),
 array([[5],
        [7],
        [9]])]

In [54]:
de=af.random.randint(0,10,(3,3))
de

array([[7, 6, 5],
       [2, 2, 7],
       [3, 4, 9]])

In [55]:
af.power(4,6)

4096

In [56]:
af.power(2,8)

256

In [57]:
# horizontal splitting
af.hsplit(de,3)

[array([[7],
        [2],
        [3]]),
 array([[6],
        [2],
        [4]]),
 array([[5],
        [7],
        [9]])]

In [63]:
# Vertical splitting
af.vsplit(de,3)

[array([[7, 6, 5]]), array([[2, 2, 7]]), array([[3, 4, 9]])]

In [64]:
af.prod(de)

635040

In [65]:
af.std(de)

2.309401076758503

In [66]:
af.var(de)

5.333333333333333

In [70]:
ab= af.array([1,2,3,2,3,4,3,4,5,6])
ba = af.array([7,2,10,2,7,4,9,4,9,8])
af.unique((ab,ba))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
names = af.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = af.random.randn(7, 4)
data[names=="Bob"]

array([[ 1.24440279, -1.34066938, -0.31962772,  0.53765665],
       [ 0.69269568, -1.01319227,  0.61175013,  0.80120306]])

In [72]:
gh=af.arange(1,16).reshape(5,3)
gh

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [73]:
xd = af.array([[1., 2., 3.], [4., 5., 6.]])
yd = af.array([[6., 23.], [-1, 7], [8, 9]])
af.dot(xd,yd)

array([[ 28.,  64.],
       [ 67., 181.]])

In [74]:
ad=af.random.gamma((5,6))
print(ad)
print('\n',ad.mean())

[4.75170116 3.4171311 ]

 4.08441613065613


In [75]:
af.median(ad)

4.08441613065613

In [77]:
af.transpose(ad)

array([4.75170116, 3.4171311 ])

In [80]:
print(af.linalg.det(abc))
print(af.linalg.det([[3,4],[5,6]]))

1.0
-1.9999999999999971


In [81]:
abc

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [84]:
af.percentile(acd,8)

4.0